[Feat]: Test action (#11)
* feat: test action

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -8,7 +8,8 @@ on:
     # Runs on pushes targeting the default branch
     push:
         branches: ['main']
-
+    pull_request:
+        branches: ['main']
     # Allows you to run this workflow manually from the Actions tab
     workflow_dispatch:
 
@@ -25,6 +26,39 @@ concurrency:
     cancel-in-progress: false
 
 jobs:
+    # Lint job
+    lint:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v2
+            - name: Detect package manager
+              id: detect-package-manager
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                    echo "manager=yarn" >> $GITHUB_OUTPUT
+                    echo "command=install" >> $GITHUB_OUTPUT
+                    echo "runner=yarn" >> $GITHUB_OUTPUT
+                    exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                    echo "manager=npm" >> $GITHUB_OUTPUT
+                    echo "command=ci" >> $GITHUB_OUTPUT
+                    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                    exit 0
+                  else
+                    echo "Unable to determine package manager"
+                    exit 1
+                  fi
+            - name: Setup Node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: '20'
+                  cache: ${{ steps.detect-package-manager.outputs.manager }}
+            - name: Install dependencies
+              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+            - name: Run unit tests
+              run: |
+                  ${{ steps.detect-package-manager.outputs.manager }} run lint
     # Build job
     build:
         runs-on: ubuntu-latest
@@ -79,15 +113,3 @@ jobs:
               uses: actions/upload-pages-artifact@v3
               with:
                   path: ./out
-
-    # Deployment job
-    deploy:
-        environment:
-            name: github-pages
-            url: ${{ steps.deployment.outputs.page_url }}
-        runs-on: ubuntu-latest
-        needs: build
-        steps:
-            - name: Deploy to GitHub Pages
-              id: deployment
-              uses: actions/deploy-pages@v4
